const FLAGS: Record<string, string> = {
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'France': '🇫🇷',
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'Spain': '🇪🇸',
  'Germany': '🇩🇪',
  'Italy': '🇮🇹',
  'Portugal': '🇵🇹',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Croatia': '🇭🇷',
  'Uruguay': '🇺🇾',
  'Colombia': '🇨🇴',
  'Chile': '🇨🇱',
  'Mexico': '🇲🇽',
  'USA': '🇺🇸',
  'Senegal': '🇸🇳',
  'Ghana': '🇬🇭',
  'Nigeria': '🇳🇬',
  'Ivory Coast': '🇨🇮',
  'Cameroon': '🇨🇲',
  'Egypt': '🇪🇬',
  'Morocco': '🇲🇦',
  'South Korea': '🇰🇷',
  'Japan': '🇯🇵',
  'Australia': '🇦🇺',
  'Denmark': '🇩🇰',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Poland': '🇵🇱',
  'Czech Republic': '🇨🇿',
  'Slovakia': '🇸🇰',
  'Hungary': '🇭🇺',
  'Romania': '🇷🇴',
  'Serbia': '🇷🇸',
  'Bosnia': '🇧🇦',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Turkey': '🇹🇷',
  'Russia': '🇷🇺',
  'Ukraine': '🇺🇦',
  'Greece': '🇬🇷',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Republic of Ireland': '🇮🇪',
  'Northern Ireland': '🇬🇧',
  'Jamaica': '🇯🇲',
  'Trinidad and Tobago': '🇹🇹',
  'Togo': '🇹🇬',
  'Mali': '🇲🇱',
  'Guinea': '🇬🇳',
  'Algeria': '🇩🇿',
  'Tunisia': '🇹🇳',
  'Gabon': '🇬🇦',
  'Congo': '🇨🇬',
  'Cape Verde': '🇨🇻',
  'Liberia': '🇱🇷',
  'Finland': '🇫🇮',
  'Iceland': '🇮🇸',
  'Israel': '🇮🇱',
  'China': '🇨🇳',
  'Iran': '🇮🇷',
  'Saudi Arabia': '🇸🇦',
  'Venezuela': '🇻🇪',
  'Paraguay': '🇵🇾',
  'Ecuador': '🇪🇨',
  'Bolivia': '🇧🇴',
  'Peru': '🇵🇪',
  'Costa Rica': '🇨🇷',
  'Honduras': '🇭🇳',
  'Panama': '🇵🇦',
  'Canada': '🇨🇦',
  'New Zealand': '🇳🇿',
  'Bulgaria': '🇧🇬',
  'Slovenia': '🇸🇮',
  'Montenegro': '🇲🇪',
  'North Macedonia': '🇲🇰',
  'Albania': '🇦🇱',
  'Luxembourg': '🇱🇺',
  'Lithuania': '🇱🇹',
  'Latvia': '🇱🇻',
  'Estonia': '🇪🇪',
  'Belarus': '🇧🇾',
  'Moldova': '🇲🇩',
  'Georgia': '🇬🇪',
  'Armenia': '🇦🇲',
  'Azerbaijan': '🇦🇿',
  'Kazakhstan': '🇰🇿',
  'Uzbekistan': '🇺🇿',
  'Zambia': '🇿🇲',
  'Zimbabwe': '🇿🇼',
  'South Africa': '🇿🇦',
  'Kenya': '🇰🇪',
  'Tanzania': '🇹🇿',
  'Uganda': '🇺🇬',
  'Ethiopia': '🇪🇹',
};

export function flag(nationality: string): string {
  return FLAGS[nationality] ?? '🌍';
}
