// ISO 3166-1 alpha-2 codes for flagsapi.com
const CODES: Record<string, string> = {
  England: 'GB',
  Scotland: 'GB',
  Wales: 'GB',
  'Northern Ireland': 'GB',
  'Republic of Ireland': 'IE',
  France: 'FR',
  Brazil: 'BR',
  Argentina: 'AR',
  Spain: 'ES',
  Germany: 'DE',
  Italy: 'IT',
  Portugal: 'PT',
  Netherlands: 'NL',
  Belgium: 'BE',
  Croatia: 'HR',
  Uruguay: 'UY',
  Colombia: 'CO',
  Chile: 'CL',
  Mexico: 'MX',
  USA: 'US',
  Canada: 'CA',
  Senegal: 'SN',
  Ghana: 'GH',
  Nigeria: 'NG',
  'Ivory Coast': 'CI',
  Cameroon: 'CM',
  Egypt: 'EG',
  Morocco: 'MA',
  Algeria: 'DZ',
  Tunisia: 'TN',
  Gabon: 'GA',
  Congo: 'CG',
  'Cape Verde': 'CV',
  Liberia: 'LR',
  Togo: 'TG',
  Mali: 'ML',
  Guinea: 'GN',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
  'South Africa': 'ZA',
  Kenya: 'KE',
  Tanzania: 'TZ',
  Uganda: 'UG',
  Ethiopia: 'ET',
  'South Korea': 'KR',
  Japan: 'JP',
  Australia: 'AU',
  'New Zealand': 'NZ',
  China: 'CN',
  Iran: 'IR',
  'Saudi Arabia': 'SA',
  Denmark: 'DK',
  Sweden: 'SE',
  Norway: 'NO',
  Poland: 'PL',
  'Czech Republic': 'CZ',
  Slovakia: 'SK',
  Hungary: 'HU',
  Romania: 'RO',
  Serbia: 'RS',
  Bosnia: 'BA',
  Switzerland: 'CH',
  Austria: 'AT',
  Turkey: 'TR',
  Russia: 'RU',
  Ukraine: 'UA',
  Greece: 'GR',
  Bulgaria: 'BG',
  Slovenia: 'SI',
  Montenegro: 'ME',
  'North Macedonia': 'MK',
  Albania: 'AL',
  Luxembourg: 'LU',
  Lithuania: 'LT',
  Latvia: 'LV',
  Estonia: 'EE',
  Belarus: 'BY',
  Moldova: 'MD',
  Georgia: 'GE',
  Armenia: 'AM',
  Azerbaijan: 'AZ',
  Kazakhstan: 'KZ',
  Uzbekistan: 'UZ',
  Jamaica: 'JM',
  'Trinidad and Tobago': 'TT',
  Venezuela: 'VE',
  Paraguay: 'PY',
  Ecuador: 'EC',
  Bolivia: 'BO',
  Peru: 'PE',
  'Costa Rica': 'CR',
  Honduras: 'HN',
  Panama: 'PA',
  Finland: 'FI',
  Iceland: 'IS',
  Israel: 'IL',
};

export function flagCode(nationality: string): string | null {
  return CODES[nationality] ?? null;
}

export function flagUrl(
  nationality: string,
  size: 16 | 24 | 32 | 48 | 64 = 24,
  style: 'flat' | 'shiny' = 'flat',
): string {
  const code = CODES[nationality];
  if (!code) return '';
  return `https://flagsapi.com/${code}/${style}/${size}.png`;
}
